### ISSUE TITLE
Icons for time, place, identifier in event details

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#10]
The status bar at the top of the detail screen shows the time, place and identifier of an event as show in the screenshot:

![eventdetails](https://user-images.githubusercontent.com/144518/29995480-5e8f0a2c-8fea-11e7-9ae3-a0fe855e6a0a.png)

# TODOs
- [x] Add meaningful and clear **icons** for each element.
- [x] Icons must be vector drawables, based on SVG.
- [x] Define custom colors for `ccc35c3` and `cccamp2019` flavors.
- [x] Test with long room names
- [x] Test on device/emulator running Android 4.0 (API level 14) and Android 10 (API level 29).

**Comment by akarsh** [comment]
I propose these two icons,
1. Time
![baseline_access_time_black_18dp](https://user-images.githubusercontent.com/845598/66056647-bd18ec80-e537-11e9-9e1e-b733501f1757.png)

URL: https://material.io/resources/icons/?icon=access_time&style=baseline

2. Room
![baseline_room_black_18dp](https://user-images.githubusercontent.com/845598/66056556-9a86d380-e537-11e9-8ac5-cdeb10af02d5.png)

URL: https://material.io/resources/icons/?icon=room&style=baseline

The background from the mock looks like a bit of cream colour - mix of gray and white. So I used the default black colour images.

Before developing, I am thinking this might be the result if i use the two icons i mentioned above,
![29995480-5e8f0a2c-8fea-11e7-9ae3-a0fe855e6a0a](https://user-images.githubusercontent.com/845598/66057332-d2424b00-e538-11e9-9853-3036bb54d065.png)

Can you guide which file to make the changes?

**Comment by johnjohndoe** [comment]
I like the icons in general. I would prefer to have bother either in outline style or in filled style for consistency reasons.
Regarding the background color please mind that it can be changed at any time. Therefore, it is important that the icons can be tinted. I am not sure if tinting is possible with the current `minSdkVersion`. Please find out if light or dark icons make sense as a default in case tinting does not work as expected.

**Comment by akarsh** [comment]
Q1. So which one to be picked for room icon. Is it fill or outline?

1. Room icon can be changed into either fill or outline
![Screen Shot 2019-10-02 at 20 57 01](https://user-images.githubusercontent.com/845598/66073380-3b38bb80-e557-11e9-9a86-3961913085a1.png)
![Screen Shot 2019-10-02 at 20 57 10](https://user-images.githubusercontent.com/845598/66073381-3b38bb80-e557-11e9-871e-b5f87d9803b4.png)

2. Time icon cannot be changed into either fill or outline
![Screen Shot 2019-10-02 at 20 58 59](https://user-images.githubusercontent.com/845598/66073547-83f07480-e557-11e9-871e-d0daf6af841f.png)
![Screen Shot 2019-10-02 at 20 59 12](https://user-images.githubusercontent.com/845598/66073548-83f07480-e557-11e9-9798-fcfd152715d7.png)


Q2. It is not worth the effort to come up with a design that would be supported by different colours. As you also need to test on all the colours if the app supports all the colours.
> Regarding the background color please mind that it can be changed at any time. Therefore, it is important that the icons can be tinted.

I could suggest a minimalist approach of following the themes i.e. light and dark supported by the google calendar app.

Example of google calendar in light and dark mode,
![Screenshot_20191002-210546](https://user-images.githubusercontent.com/845598/66075307-98367080-e55b-11e9-965b-869cb4feac57.png)
![Screenshot_20191002-210640](https://user-images.githubusercontent.com/845598/66075308-98367080-e55b-11e9-9a3f-7c63b79a709b.png)

If you support these two themes, the app could be tested against the colours suggested in material design website - https://material.io/design/color/dark-theme.html#

Q3. Decision on supported colours. Which colours from material palette - https://material.io/resources/color/#!/?view.left=0&view.right=0

This would make it easy to complie with the  Legibility standards  - https://material.io/design/color/text-legibility.html#legibility-standards mentioned in the material design.
