### ISSUE TITLE
Use targetSdkVersion 28 (Pie)

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#138]
# Background
- [Expanding target API level requirements in 2019](https://android-developers.googleblog.com/2019/02/expanding-target-api-level-requirements.html)
- [Target API level requirements for the Play Console](https://support.google.com/googleplay/android-developer/answer/113469#targetsdk)
- [Meet Google Play's target API level requirement](https://developer.android.com/distribute/best-practices/develop/target-sdk)

# Current state
- `targetSdkVersion 27`

# Target state
- [x] `targetSdkVersion 28`
  - [x] [Opt out of cleartext traffic](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted), [Android 8: Cleartext HTTP traffic not permitted](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted)
- [x] Remove/replace deprecated code with new APIs.
  - [x] [android.preference.PreferenceFragment](https://developer.android.com/reference/android/preference/PreferenceFragment) -> used in `SettingsActivity` -> Moved to #162.
  - [x] [android.app.Activity#getFragmentManager](https://developer.android.com/reference/android/app/Activity#getFragmentManager()) -> used in `SettingsActivity` -> Moved to #162.
  - [x] [android.net.ConnectivityManager#CONNECTIVITY_ACTION](https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION) -> used in `ConnectivityStateReceiver` (2x)
  - [x] [android.net.NetworkInfo#isConnectedOrConnecting](https://developer.android.com/reference/android/net/NetworkInfo#isConnectedOrConnecting()) -> used in `Connectivity.kt`
  - [x] https://developer.android.com/reference/android/net/NetworkInfo
- [x] Update [Support Library to 28.0.0](https://developer.android.com/topic/libraries/support-library/revisions#28-0-0).
  - [x] Use `ContextCompat.getSystemService()`.
- [x] Update [SnackEngage](https://github.com/ligi/SnackEngage) once [a new version depending on Support Library 28.0.0](https://github.com/ligi/SnackEngage/pull/35) is out.
- [x] Check documentation for changes and add here.

# Related
- [Issue #137: Use targetSdkVersion 27 (Oreo)](https://github.com/EventFahrplan/EventFahrplan/issues/137)

**Comment by johnjohndoe** [comment]
> Opt out of cleartext traffic, Android 8: Cleartext HTTP traffic not permitted

Nothing to do now.
