### ISSUE TITLE
Replace deprecated "android.preference" API

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#162]
# TODOs

- [x] Remove/replace deprecated code with new APIs of [`androidx.preference`](https://developer.android.com/reference/androidx/preference/package-summary).
  - [x] [`android.preference.PreferenceFragment`](https://developer.android.com/reference/android/preference/PreferenceFragment) -> used in `SettingsActivity`
  - [x] [`android.app.Activity#getFragmentManager`](https://developer.android.com/reference/android/app/Activity#getFragmentManager()) -> used in `SettingsActivity`
 - [x] Update custom `EditTextPreference` -> `ValidateableEditTextPreference`
- [x] Figure out how to migrate `RingtonePreference`
- [x] Check functionality on older Android versions
- [x] Check that `hint` is still shown in `EditTextPreference`
- [x] Check if text and background colors in Settings are set correctly on older Android versions

# Related
- [Issue #273: Use targetSdkVersion 29, Android 10](https://github.com/EventFahrplan/EventFahrplan/issues/273)
- [Android Developer / Docs / Settings](https://developer.android.com/guide/topics/ui/settings)
- [Material Design / Android settings](https://material.io/design/platform-guidance/android-settings.html)
- [androidx.preference release notes](https://developer.android.com/jetpack/androidx/releases/preference)
- [The `android.preference` library is deprecated as of Android 10.](https://developer.android.com/about/versions/10/behavior-changes-all#preferences)
- [Android issue #162566191: Cannot find equivalent of the deprecated PreferenceActivity in androidx.](https://issuetracker.google.com/issues/162566191)
- [Android Settings using PreferenceFragmentCompat](https://storiesandroid.wordpress.com/2015/10/06/android-settings-using-preference-fragments/)
- [Validating EditTextPreference on Android](https://stackoverflow.com/questions/21856932/validating-edittextpreference-android)
- [Android issue #37060038: preference-v7 EditTextPreference does not forward xml attributes to EditText](https://issuetracker.google.com/issues/37060038)
- [Android Developer / Docs / Customize an EditTextPreference dialog](https://developer.android.com/guide/topics/ui/settings/customize-your-settings#customize_an_edittextpreference_dialog)

## RingtonePreference
- [How to implement RingtonePreference in PreferenceFragmentCompat?](https://stackoverflow.com/questions/35692522/how-to-implement-ringtonepreference-in-preferencefragmentcompat)
  - [Android issue #37057453: No support for RingtonePreference in support library](https://issuetracker.google.com/issues/37057453)
- [Android Developer / Docs / PickRingtone example](https://developer.android.com/training/basics/intents/result#custom)
- [Issue #124: Custom alarm tone is not used](https://github.com/EventFahrplan/EventFahrplan/issues/124)
