### ISSUE TITLE
Show own shifts from Engelsystem

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#181]
# Context
The [Engelsystem](https://engelsystem.de) is used to coordinate volunteers and work shifts at large events such as the [Chaos Communication Congress](https://en.wikipedia.org/wiki/Chaos_Communication_Congress). The Engelsystem exposes the shifts of its users via an API. It is considered helpful to integrate the shifts as a separate column in the main schedule view. It must be possible to enable or disable this feature for different flavors of the app since not all events use the Engelsystem.

# TODOs
- [x] A [staging environment](https://staging.engelsystem.de/test) can be used for testing. :vertical_traffic_light: 
- [x] A [standalone Kotlin library](https://github.com/johnjohndoe/engelsystem) has been prepared ~~(pre-alpha status)~~ :package: 
  - Parses the API response
  - Provides data models
- [x] First work has been done on a branch. Work in progress will be published soon. :hourglass_flowing_sand: 
  - https://github.com/EventFahrplan/EventFahrplan/tree/engelsystem-shifts
- [x] Add boolean `buildConfigField` field to allow switching on/off this feature.
  - Show/hide settings option
  - Enable/disable loading shifts
- [x] Integrate library as a separate `:engelsystem` module.
- [x] Integrate loading shifts in `AppRepository`, 
  - map library models to app models (`nerd.tuxmobil.fahrplan.congress.models.Lecture`)
- [x] UI: Add settings option to allow users to enter their API token
  - Is rather long: 33 characters. What would be a user-friendly way to enter the token?
  - For now users have to paste or enter the full URL string.
- [x] Validate shift URL entered by users.
- [x] Test how shift updates (additions, changes, deletions) are handled.
  - Old shifts are dropped when new are loaded.
- [x] Decide if shifts which take place before or after the event are displayed.
  - Shifts before and after the main event days will not be displayed.
- [x] Ask API developer for ETAG support.
   - https://github.com/engelsystem/engelsystem/issues/677
- [x] Ask API developer for time zone offset support.
   - https://github.com/engelsystem/engelsystem/issues/689
   - https://github.com/johnjohndoe/engelsystem/pull/2
- [x] Test with real shift data (from former events?).
- [x] Test without WiFi connection.

### Last before merging
- [x] Test release build.
- [x] Test app update.

## Known challenges
- [x] Updating the room index defined by the general schedule for the new shift column without messing up the database entries of existing sessions.
  - The main schedule is shifted by 1 when any Engelsystem shifts are present at that particular day.
- [x] Handling loading the general schedule or the shifts first.
  - Shifts are only loaded once the schedule has been retrieved.
- [x] ~~Shifts can have overlapping end and start times! Clean-up by the app needed.~~
  - Considered an edge case. Therefore not addressed for the first implementation. :triangular_flag_on_post: 
- [x] Certificate check for two domains
  - Handled by the Android system + OkHttp.

# Related
- [Issue #30: Feature: Add favourites to calendar](https://github.com/EventFahrplan/EventFahrplan/issues/30)
