### ISSUE TITLE
Modernize testing infrastructure

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#251]
# Current state
- Unit test are based on [JUnit 4](https://junit.org/junit4/).

# Target state
- Unit test are based on [JUnit 5](https://junit.org/junit5/).

## TODOs
- [x] Migrate primitive unit tests
- [x] Migrate `MainDispatcherTestRule` test to JUnit 5 extension
- [x] Migrate instrumentation tests
- [x] Migrate parameterized tests
- [x] Remove JUnit 4 dependencies
- [x] Verify number of tests before and after the migration match (aka. all are still executed) 
- [x] Verify JaCoCo test report still works
- [x] Verify GitHub action still collects unit test results

# Hints
- Keep commits and pull requests small and enjoyable to review.
  - Create commits per TODO topic or 
  - Migrate each module separately 
- Starting to work on this issue has to be coordinated with work being done in issue #141.

# Related
- [Issue #141: Assertion library update](https://github.com/EventFahrplan/EventFahrplan/issues/141)

# Resources
- [JUnit 5 user guide](https://junit.org/junit5/docs/current/user-guide/)
- [mannodermaus/android-junit5](https://github.com/mannodermaus/android-junit5)
- [GitHub Action to Publish Test Results](https://github.com/EnricoMi/publish-unit-test-result-action)
- [Getting Started with AndroidX Test](https://victoriagonda.com/talks/androidx_test.html)
