### ISSUE TITLE
Migrate project to AndroidX

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#265]
# Background
- Development for Android Support Library has stopped with version 28.0.0.
- Improvements and new features are only available via AndroidX libraries (JetPack).

# Prerequisites
- `compileSdkVersion` 28 & `targetSdkVersion 28`
- Everybody should have their branches being merged before this migration starts to avoid complicated rebase sessions. :speech_balloon: Talk to project members before you start!

# TODOs
- [x] Use Android Studio migration wizard.
  - Use AndroidX library version 1.0.0 which is binary equivalent to 28.0.0. Do not use the latest versions.
- [x] Update `Dependencies.kt` and `build.gradle` files. Extract dependency declararations. Remove unused.
- [x] Organize imports.
- [x] Remove `android.useAndroidX=true` and `android.enableJetifier=true` if not needed.
- [x] Update ProGuard rules in `app/proguard-rules/`.
- [x] Update [SnackEngage](https://github.com/ligi/SnackEngage): `0.22`-> `0.23`.
- [x] Check for deprecations via Lint and in build output. -> No new deprecations introduced in migration.
- [x] Run unit tests.
- [x] Run instrumentation tests (`database` module).
- [x] Test release build.

# Documentation
- [Migrating to AndroidX](https://developer.android.com/jetpack/androidx/migrate)
- [Artifact Mappings](https://developer.android.com/jetpack/androidx/migrate/artifact-mappings)
- [AndroidX Releases](https://developer.android.com/jetpack/androidx/versions)
