### ISSUE TITLE
Remove kotlin-coroutines-retrofit dependency

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#271]
# Current state
- [`ru.gildor.coroutines:kotlin-coroutines-retrofit:1.1.0`](https://github.com/gildor/kotlin-coroutines-retrofit) is used in `EngelsystemNetworkRepository` in the `engelsystem` module. The library depends on [`org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1`](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.1.1) which was released 24.01.2019.
- [Development of the library is discontinued](https://github.com/gildor/kotlin-coroutines-retrofit/pull/57#pullrequestreview-331689298) because Retrofit introduced `<T : Any> Call<T>.await*()` extension functions in version [2.6.0](https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-260-2019-06-05) itself. See https://github.com/square/retrofit/commit/b761518aa174c7b0512b73f2fe70e2e908f24081.
- `com.squareup.retrofit2:retrofit:2.6.4` is used as a transitive dependency of `info.metadude.kotlin.library.engelsystem:engelsystem-base:3.1.0`.

# Target state
- Use Retrofit's functions to replace `kotlin-coroutines-retrofit`.

# TODOs
- [x] Replace `kotlin-coroutines-retrofit`'s `awaitResult` with `retrofit`'s `awaitResponse` function.
- [x] Add unit tests.
- [x] Manually test if the Engelsystem feature still works. @johnjohndoe can provide access to a test backend.
