### ISSUE TITLE
Use targetSdkVersion 29, Android 10

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#273]
:calendar: Due before November 2, 2020.

# :no_good: Blocked by
- ~~[Issue #256: Migrate project to AndroidX]( https://github.com/EventFahrplan/EventFahrplan/issues/265)~~ :heavy_check_mark: 
- ~~[Issue #162: Replace deprecated "android.preference" API](https://github.com/EventFahrplan/EventFahrplan/issues/162)~~ :heavy_check_mark: 

# Background
- [Meet Google Play's target API level requirement](https://developer.android.com/distribute/best-practices/develop/target-sdk.html)
- [Target API level requirements for the Play Console](https://support.google.com/googleplay/android-developer/answer/113469#targetsdk)
- [Android 10 highlights for developers](https://developer.android.com/about/versions/10/highlights)
  - `Android 10 adds a system-wide dark theme that’s ideal for low light and helps save battery`
- [Android 10 behavior changes: all apps](https://developer.android.com/about/versions/10/behavior-changes-all)
  - `TLS 1.3 is enabled by default for all TLS connections`
  - `Certificates that use the SHA-1 hash algorithm aren't trusted in TLS connections`
- [Android 10 behavior changes: apps targeting API 29+](https://developer.android.com/about/versions/10/behavior-changes-10)
- [Android 10 features and APIs](https://developer.android.com/about/versions/10/features)
  - `Android 10 improves the coverage of nullability annotations in the SDK for libcore APIs`

# Current state
- `targetSdkVersion 28`

# Target state
- [x] `targetSdkVersion 29`
- [x] Remove/replace deprecated code with new APIs.
  - [x] Use new `Activity#setShowWhenLocked` method to show map on lock screen. -> #304
  - [x] Replace deprecated `Html#fromHtml` with `HtmlCompat#fromHtml`. -> #294
  - [x] Use [AndroidX preference](https://developer.android.com/jetpack/androidx/releases/preference) library. [The `android.preference` library is deprecated as of Android 10.](https://developer.android.com/about/versions/10/behavior-changes-all#preferences) -> #312 
  - [x] Inspect for new deprecations via `-Xlint:deprecation`. -> No new deprecations found comparing SDK 28 with 29.
- [x] Check documentation for changes and add here.

# Related
- [Issue #138: Use targetSdkVersion 28 (Pie)](https://github.com/EventFahrplan/EventFahrplan/issues/138)
- [Issue #162: Replace deprecated "android.preference" API](https://github.com/EventFahrplan/EventFahrplan/issues/162)
