### ISSUE TITLE
Adjust clock/time icon positioning and spacing

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#318]
# Description
- The clock icon which is used in the session details screen looks somewhat odd positioned.

  ![Session details clock icon](https://user-images.githubusercontent.com/144518/93663005-ba731800-fa64-11ea-8204-3dd56b97efc4.png)

# TODOs
- [x] Adjust either the SVG icon itself or the positioning or spacing.
- [x] Check different layout files for smartphones and tablets
- [x] Check the spacing with different leading numbers in the text string (hardcoding text temporary is fine)
- [x] Provide screenshots of before and after in your pull request

# Hints
- Resources to start of with
  - assets/access-time.svg
  - drawable/ic_access_time.xml
  - app/src/main/res/layout/session_detailbar.xml
  - app/src/main/res/layout/session_detailbar_large.xml
  - tbc.

**Comment by minibugdev** [comment]
I am working on this"
