### ISSUE TITLE
Migrate from id to guid

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#319]
# Status
- :construction: Draft - details to be discussed and written down here.

# Current state
- The `id` XML attribute is parsed from the schedule XML and used with the app (_details tbd._).
- `id` values are not guaranteed to be unique - `id` values used for different sessions cause errors.

# Target state
- The `guid` XML attribute is parsed from the schedule XML and used with the app (_details tbd._).

# TODOs
- [ ] Parse `guid` XML attribute.
- [ ] Use `guid` within the app (_details tbd._)
- [ ] Display `guid` value (?)
- [ ] Check if `id` XML attribute can be removed.

# Related
- [voc/schedule issue #63: Duplicate event ids (36C3)](https://github.com/voc/schedule/issues/63)

**Comment by johnjohndoe** [comment]
@NiciDieNase Can you tell if the [JSON import in the Chaosflix](https://github.com/EventFahrplan/EventFahrplan/pull/241) app will be broken when I move from `id` to `guid` here?

**Comment by cketti** [comment]
I think a better approach would be to use an auto-incrementing INTEGER column to uniquely identify a session in the database. This will keep the app simple in situations where stable numeric identifiers are required or at least very helpful (e.g. in a `RecyclerView.Adapter`).

This way only the code that maps between network model and app model has to be aware of GUIDs. If the identifier in the network format changes in the future only the mapping code needs to be updated.

Using that approach also allows splitting this change into two parts:
1. Change app to use its own unique session ID.
2. Change mapping code to use `guid` attribute instead of `id` attribute for matching items.

**Comment by johnjohndoe** [comment]
:firefighter: This has become top priority because the merged schedule data for the upcoming [rc3](https://events.ccc.de/2020/09/04/rc3-remote-chaos-experience/) will **not** contain `id` attributes for all XML `event` nodes - but `guid` attributes!

**Comment by johnjohndoe** [comment]
I extended the information in the "current state" section to clarify the currently used mechanism.

**Comment by NiciDieNase** [comment]
> @NiciDieNase Can you tell if the [JSON import in the Chaosflix](https://github.com/EventFahrplan/EventFahrplan/pull/241) app will be broken when I move from `id` to `guid` here?

No, should not be affected, chaoflix uses guid for importing.

**Comment by johnjohndoe** [comment]
@cketti The work-in-progress of a new implementation can be found on the [`id-guid-migration-v2` branch](https://github.com/EventFahrplan/EventFahrplan/compare/id-guid-migration-v2).

**Comment by johnjohndoe** [comment]
# :speaker: Update
- The aggregated schedule for the `rc3` event has been adapted.
- `id` values are [derived from `guid` values](https://github.com/voc/schedule/commit/0cbecc7eb7dc02b78db114395887e4018c01a3cc#diff-d1ae209f86fbd73d4afbfea42124e705a27cf91aa54399e7a801f88d70b4db64R382) to support the usage of `id` in client applications.
- The `id` is generated from the first **six numbers** found in the `guid` string.
- I will test the schedule data and probably postpone the migration because there are still unresolved issues in PR #350.

**Comment by saerdnaer** [comment]
@johnjohndoe Whats the current state of this issue?

**Comment by johnjohndoe** [comment]
@saerdnaer Paused. I will pick up work on the topic again in October 2021.

**Comment by johnjohndoe** [comment]
@saerdnaer I haven't been able to continue here. I likely have to stick to IDs for rC3.rev2.
