### ISSUE TITLE
Configure code coverage with JaCoCo

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#386]
# Current state
- The project is configured for https://sonarcloud.io via [_gradle/sonarqube.gradle_](https://github.com/EventFahrplan/EventFahrplan/blob/master/gradle/sonarqube.gradle). See https://sonarcloud.io/dashboard?id=eventfahrplan.
- SonarQube is being used from time to time to check the current statistics. This happens by manually executing either `./gradlew sonarqube` on the `master` branch or `./gradlew sonarqube -Dsonar.branch.name=feature-x` on a feature branch.
- SonarQube/SonarCloud does not recognize code coverage:
![image](https://user-images.githubusercontent.com/144518/114550025-06d0b000-9c62-11eb-8e3e-9a0e7b4bb5e2.png)
- The `com.vanniktech:gradle-android-junit-jacoco-plugin` Plugin is used to generate code coverage reports locally by executing one of the `jacocoTestReport` Gradle tasks.

# TODOs
- [ ] Check if SonarCloud allows that multiple people can push updates.
- [ ] Configure the project so code coverage is tracked every time `./gradlew sonarqube` is executed.
- [ ] Ensure code coverage reports generated locally still work in the browser.
- [ ] Check if code coverage can be generated for all modules (Java, Kotlin, Android).
- [ ] Check if a merged (single file) code coverage report can be generated for all modules.

# Resources
An unsorted list of websites which might be helpful to resolve above tasks.
- https://github.com/vanniktech/gradle-android-junit-jacoco-plugin
- https://github.com/autonomousapps/jacoco-android-gradle-plugin
- https://github.com/covidwatchorg/covidwatch-android-tcn/blob/develop/build.gradle
- https://github.com/hishambakr/SonarCloudDemoAndroid/blob/main/build.gradle
- https://stackoverflow.com/questions/58839685/how-to-configure-sonar-coverage-jacoco-xmlreportpaths-for-jacoco-sonarqube
- https://community.sonarsource.com/t/sonar-coverage-jacoco-xmlreportpaths-not-showing-code-coverage-but-the-deprecated-sonar-jacoco-reportpaths-shows-code-coverage/12938/43
- https://stackoverflow.com/questions/60324076/how-to-build-jacoco-test-report-task-in-kotlin-gradle-5/60327178#60327178
- https://jira.sonarsource.com/browse/MMF-1651
- https://community.sonarsource.com/t/coverage-test-data-importing-jacoco-coverage-report-in-xml-format/12151
- https://mkyong.com/maven/maven-jacoco-code-coverage-example/
- https://github.com/SkarCBR/app-analyzer/blob/b1f53aff5d9c91e5c4862620ee5fc77fe972883f/src/main/kotlin/com/justpinch/AndroidAnalyzer.kt#L401
- https://stackoverflow.com/questions/28085349/jacoco-code-coverage-in-android-studio-with-flavors

**Comment by johnjohndoe** [comment]
Configuration draft:

``` groovy
apply plugin: "org.sonarqube"

sonarqube {
    androidVariant "cccamp2023Debug"
    properties {
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.organization", "eventfahrplan"
        property "sonar.projectKey", "eventfahrplan"
        property "sonar.projectName", "EventFahrplan"
        property "sonar.projectVersion", APP_VERSION
        property "sonar.androidLint.reportPaths", "${project.buildDir}/reports/lint-results-cccamp2023Debug.xml"
    }
}
```
