### ISSUE TITLE
Recreate alarms screen

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#512]
# Preconditions
- MinSdk 21 (currently 16) -> Pull request #547 

# Current state
- The alarm screen has been built a long time ago and must be rebuilt to be maintainable.
- Classes like `CursorAdapter` and `android.widget.ListView` are used.
- The alarm screen appears and behaves different compared to similar screens such as "favorites" or "schedule changes".
- Feature set:
  - List of alarms. Each entry show the alarm time, alarm time offset in minutes, session title, session subtile.
  - Delete individual alarms.
  - Delete all alarms at once via the overflow menu.

# Target state
- The new alarm screen is built on the principles of modern Android architecture.
- The new screen architecture must be a "template" for similar screens such as "favorites" or "schedule changes" to be updated in the future.
- The new alarm screen appears as a (side) fragment like screens such as "favorites" or "schedule changes".
- The new alarm screen works both for phones and tablets.

## TODOs
- [x] Compose project setup integrated in former XML layout project setup
- [x] Activity / Fragment + ViewModel
- [x] Observable properties + database functions exposes by repository
- [x] UI state data class (Loading, Success, ...)
- [x] UI state payload class (view specific data)
- [x] UI implementation with Compose UI + previews
- [x] Delete unused files (adapter, repository functions (?), layouts, ...)
- [x] Alarms icon with alarm time offset
- [x] Delete icon
- [x] Select alarm entry -> navigate to associated session details screen
- [x] Unit test ViewModel
- [x] Content description (Accessibility, TalkBack) for alarm entries.
- [ ] ~App Theme to be used by Compose UI and to be customizable via build flavors~

# Technology discussion
- :heavy_check_mark: The screen could be recreated using modern [`RecyclerView`](https://developer.android.com/develop/ui/views/layout/recyclerview), `ViewModel` classes and by introducing [Compose UI](https://developer.android.com/jetpack/compose) (requires `minSdk 21`) to the code base. This needs to be discussed before work is started.
